# Generated by Django 4.0.5 on 2022-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['date'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['date'], name='posts_date_time_idx'),
        ),
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
