# Generated by Django 4.0.5 on 2022-08-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_posts_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
